import { Injectable } from '@angular/core';
import { Seat } from '../models/seat.model';
import { SeatTypeService } from './seat-type.service';
import { SeatType } from '../models/seat-type';
import { CinemaBookingService } from './cinema-booking.service';
import { Booking } from '../models/booking';

@Injectable({
  providedIn: 'root',
})
export class CinemaSeatService {
  private seatTypeList: SeatType[] = this.seatTypeService.getList();

  private seatList: Seat[] = [
    {
      id: 1,
      cinameId: 1,
      name: 'A01',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 2,
      cinameId: 1,
      name: 'A02',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 3,
      cinameId: 1,
      name: 'A03',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 4,
      cinameId: 1,
      name: 'A04',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 5,
      cinameId: 1,
      name: 'A05',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 6,
      cinameId: 1,
      name: 'A06',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 7,
      cinameId: 1,
      name: 'A07',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 8,
      cinameId: 1,
      name: 'A08',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 9,
      cinameId: 1,
      name: 'A09',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 10,
      cinameId: 1,
      name: 'A10',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 11,
      cinameId: 1,
      name: 'A11',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 12,
      cinameId: 1,
      name: 'A12',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 13,
      cinameId: 1,
      name: 'A13',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 14,
      cinameId: 1,
      name: 'A14',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 15,
      cinameId: 1,
      name: 'A15',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 16,
      cinameId: 1,
      name: 'A16',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 17,
      cinameId: 1,
      name: 'B01',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 18,
      cinameId: 1,
      name: 'B02',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 19,
      cinameId: 1,
      name: 'B03',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 20,
      cinameId: 1,
      name: 'B04',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 21,
      cinameId: 1,
      name: 'B05',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 22,
      cinameId: 1,
      name: 'B06',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 23,
      cinameId: 1,
      name: 'B07',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 24,
      cinameId: 1,
      name: 'B08',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 25,
      cinameId: 1,
      name: 'B09',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 26,
      cinameId: 1,
      name: 'B10',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 27,
      cinameId: 1,
      name: 'B11',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 28,
      cinameId: 1,
      name: 'B12',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 29,
      cinameId: 1,
      name: 'B13',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 30,
      cinameId: 1,
      name: 'B14',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 31,
      cinameId: 1,
      name: 'B15',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 32,
      cinameId: 1,
      name: 'B16',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 33,
      cinameId: 1,
      name: 'C01',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 34,
      cinameId: 1,
      name: 'C02',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 35,
      cinameId: 1,
      name: 'C03',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 36,
      cinameId: 1,
      name: 'C04',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 37,
      cinameId: 1,
      name: 'C05',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 38,
      cinameId: 1,
      name: 'C06',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 39,
      cinameId: 1,
      name: 'C07',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 40,
      cinameId: 1,
      name: 'C08',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 41,
      cinameId: 1,
      name: 'C09',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 42,
      cinameId: 1,
      name: 'C10',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 43,
      cinameId: 1,
      name: 'C11',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 44,
      cinameId: 1,
      name: 'C12',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 45,
      cinameId: 1,
      name: 'C13',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 46,
      cinameId: 1,
      name: 'C14',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 47,
      cinameId: 1,
      name: 'C15',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 48,
      cinameId: 1,
      name: 'C16',
      type: this.seatTypeList[0],
      status: 1,
    },
    {
      id: 49,
      cinameId: 1,
      name: 'M01',
      type: this.seatTypeList[2],
      status: 1,
    },
    {
      id: 50,
      cinameId: 1,
      name: 'M02',
      type: this.seatTypeList[2],
      status: 1,
    },
    {
      id: 51,
      cinameId: 1,
      name: 'M03',
      type: this.seatTypeList[2],
      status: 1,
    },
    {
      id: 52,
      cinameId: 1,
      name: 'M04',
      type: this.seatTypeList[2],
      status: 1,
    },
    {
      id: 53,
      cinameId: 1,
      name: 'M05',
      type: this.seatTypeList[2],
      status: 1,
    },
    {
      id: 54,
      cinameId: 1,
      name: 'M06',
      type: this.seatTypeList[2],
      status: 1,
    },
    {
      id: 55,
      cinameId: 1,
      name: 'M07',
      type: this.seatTypeList[2],
      status: 1,
    },
    {
      id: 56,
      cinameId: 1,
      name: 'M08',
      type: this.seatTypeList[2],
      status: 1,
    },
    {
      id: 57,
      cinameId: 2,
      name: 'A01',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 58,
      cinameId: 2,
      name: 'A02',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 59,
      cinameId: 2,
      name: 'A03',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 60,
      cinameId: 2,
      name: 'A04',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 61,
      cinameId: 2,
      name: 'A05',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 62,
      cinameId: 2,
      name: 'A06',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 63,
      cinameId: 2,
      name: 'A07',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 64,
      cinameId: 2,
      name: 'A08',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 65,
      cinameId: 2,
      name: 'A09',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 66,
      cinameId: 2,
      name: 'A10',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 67,
      cinameId: 2,
      name: 'A11',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 68,
      cinameId: 2,
      name: 'A12',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 69,
      cinameId: 2,
      name: 'A13',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 70,
      cinameId: 2,
      name: 'A14',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 71,
      cinameId: 2,
      name: 'A15',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 72,
      cinameId: 2,
      name: 'A16',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 73,
      cinameId: 2,
      name: 'B01',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 74,
      cinameId: 2,
      name: 'B02',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 75,
      cinameId: 2,
      name: 'B03',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 76,
      cinameId: 2,
      name: 'B04',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 77,
      cinameId: 2,
      name: 'B05',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 78,
      cinameId: 2,
      name: 'B06',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 79,
      cinameId: 2,
      name: 'B07',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 80,
      cinameId: 2,
      name: 'B08',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 81,
      cinameId: 2,
      name: 'B09',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 82,
      cinameId: 2,
      name: 'B10',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 83,
      cinameId: 2,
      name: 'B11',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 84,
      cinameId: 2,
      name: 'B12',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 85,
      cinameId: 2,
      name: 'B13',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 86,
      cinameId: 2,
      name: 'B14',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 87,
      cinameId: 2,
      name: 'B15',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 88,
      cinameId: 2,
      name: 'B16',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 89,
      cinameId: 2,
      name: 'C01',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 90,
      cinameId: 2,
      name: 'C02',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 91,
      cinameId: 2,
      name: 'C03',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 92,
      cinameId: 2,
      name: 'C04',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 93,
      cinameId: 2,
      name: 'C05',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 94,
      cinameId: 2,
      name: 'C06',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 95,
      cinameId: 2,
      name: 'C07',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 96,
      cinameId: 2,
      name: 'C08',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 97,
      cinameId: 2,
      name: 'C09',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 98,
      cinameId: 2,
      name: 'C10',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 99,
      cinameId: 2,
      name: 'C11',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 100,
      cinameId: 2,
      name: 'C12',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 101,
      cinameId: 2,
      name: 'C13',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 102,
      cinameId: 2,
      name: 'C14',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 103,
      cinameId: 2,
      name: 'C15',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 104,
      cinameId: 2,
      name: 'C16',
      type: this.seatTypeList[1],
      status: 1,
    },
    {
      id: 105,
      cinameId: 2,
      name: 'M01',
      type: this.seatTypeList[3],
      status: 1,
    },
    {
      id: 106,
      cinameId: 2,
      name: 'M02',
      type: this.seatTypeList[3],
      status: 1,
    },
    {
      id: 107,
      cinameId: 2,
      name: 'M03',
      type: this.seatTypeList[3],
      status: 1,
    },
    {
      id: 108,
      cinameId: 2,
      name: 'M04',
      type: this.seatTypeList[3],
      status: 1,
    },
    {
      id: 109,
      cinameId: 2,
      name: 'M05',
      type: this.seatTypeList[3],
      status: 1,
    },
    {
      id: 110,
      cinameId: 2,
      name: 'M06',
      type: this.seatTypeList[3],
      status: 1,
    },
    {
      id: 111,
      cinameId: 2,
      name: 'M07',
      type: this.seatTypeList[3],
      status: 1,
    },
    {
      id: 112,
      cinameId: 2,
      name: 'M08',
      type: this.seatTypeList[3],
      status: 1,
    },
  ];

  constructor(
    private seatTypeService: SeatTypeService,
    private cinemaBookingService: CinemaBookingService
  ) {}

  getList(): Seat[] {
    return this.seatList;
  }

  getSeatById(id?: number): Seat | undefined {
    return this.seatList.find(s => {
      return s.id == id
    })
  }

  getSeatListForBooking(cinemaId: number, showtimeId: number): Seat[] {
    let seats: Seat[] = [];

    this.seatList.forEach((seat) => {
      if (seat.cinameId == cinemaId) {
        seats.push({
          id: seat.id,
          cinameId: seat.cinameId,
          name: seat.name,
          type: seat.type,
          status: seat.status,
        });
      }
    });

    let bookings: Booking[] =
      this.cinemaBookingService.getBookedSeat(showtimeId);

    seats.forEach((seat) => {
      bookings.forEach((booking) => {
        booking.bookingDetails.forEach((details) => {
          if (details.seat.id == seat.id) {
            seat.status = 2;
          }
        });
      });
    });

    return seats;
  }
}
